org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=witcherywalls
mod_name=Witchery Walls
mod_license=GNU GPL v3
mod_version=1.20.1-1.2.0
mod_group_id=com.witcherywalls
mod_authors=Astryxion
mod_credits=Astryxion, Almightytallestred, Emoniph
mod_homepage=https://github.com/astryxion/Witchery-Villages
mod_description=Fortifies generated villages with walls, town keeps, guard towers, and villager guards. Highly configurable, with compatibility for Guard Villagers.
